const ADD_ITEM_TODO = "ADD_ITEM_TODO";
const REMOVE_ITEM_TODO = "REMOVE_ITEM_TODO";
const CHANGE_ITEM_TODO = "CHANGE_ITEM_TODO";

const ADD_ITEM_DOING = "ADD_ITEM_DOING";
const REMOVE_ITEM_DOING = "REMOVE_ITEM_DOING";
const CHANGE_ITEM_DOING = "CHANGE_ITEM_DOING";

export {
  ADD_ITEM_TODO,
  REMOVE_ITEM_TODO,
  CHANGE_ITEM_TODO,

  ADD_ITEM_DOING,
  REMOVE_ITEM_DOING,
  CHANGE_ITEM_DOING,
}
