const ADD_ITEM_TODO = "ADD_ITEM_TODO";
const REMOVE_ITEM_TODO = "REMOVE_ITEM_TODO";
const CHANGE_ITEM_TODO = "CHANGE_ITEM_TODO";

const ADD_ITEM_DOING = "ADD_ITEM_DOING";
const REMOVE_ITEM_DOING = "REMOVE_ITEM_DOING";
const CHANGE_ITEM_DOING = "CHANGE_ITEM_DOING";

const ADD_ITEM_DONE = "ADD_ITEM_DONE";
const REMOVE_ITEM_DONE = "REMOVE_ITEM_DONE";
const CHANGE_ITEM_DONE = "CHANGE_ITEM_DONE";

export {
  ADD_ITEM_TODO,
  REMOVE_ITEM_TODO,
  CHANGE_ITEM_TODO,

  ADD_ITEM_DOING,
  REMOVE_ITEM_DOING,
  CHANGE_ITEM_DOING,

  ADD_ITEM_DONE,
  REMOVE_ITEM_DONE,
  CHANGE_ITEM_DONE,
}
